/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author carlo
 */
public class VRegistro extends javax.swing.JPanel {

    /**
     * Creates new form VRegistro
     */
    public VRegistro() {
        initComponents();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        textoUsuario6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoUsuario7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        textoUsuario8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        textoUsuario9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        textoUsuario10 = new javax.swing.JLabel();
        textoUsuario11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoUsuario6.setBackground(new java.awt.Color(65, 105, 225));
        textoUsuario6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textoUsuario6.setForeground(new java.awt.Color(65, 105, 225));
        textoUsuario6.setText("Registro de un nuevo usuario");
        panelRegistro.add(textoUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelRegistro.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 220, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_User_32px.png"))); // NOI18N
        panelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        textoUsuario7.setBackground(new java.awt.Color(65, 105, 225));
        textoUsuario7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textoUsuario7.setForeground(new java.awt.Color(65, 105, 225));
        textoUsuario7.setText("Nombre:");
        panelRegistro.add(textoUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelRegistro.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 220, 30));

        textoUsuario8.setBackground(new java.awt.Color(65, 105, 225));
        textoUsuario8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textoUsuario8.setForeground(new java.awt.Color(65, 105, 225));
        textoUsuario8.setText("DNI:");
        panelRegistro.add(textoUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelRegistro.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 220, 30));

        textoUsuario9.setBackground(new java.awt.Color(65, 105, 225));
        textoUsuario9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textoUsuario9.setForeground(new java.awt.Color(65, 105, 225));
        textoUsuario9.setText("ID:");
        panelRegistro.add(textoUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelRegistro.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 220, 30));

        textoUsuario10.setBackground(new java.awt.Color(65, 105, 225));
        textoUsuario10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textoUsuario10.setForeground(new java.awt.Color(65, 105, 225));
        textoUsuario10.setText("Email:");
        panelRegistro.add(textoUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        textoUsuario11.setBackground(new java.awt.Color(65, 105, 225));
        textoUsuario11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textoUsuario11.setForeground(new java.awt.Color(65, 105, 225));
        textoUsuario11.setText("Teléfono:");
        panelRegistro.add(textoUsuario11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        panelRegistro.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 220, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Unchecked_Checkbox_36px_1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRegistro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 30, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Checked_Checkbox_36px_1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRegistro.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 30, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/captcha_1.JPG"))); // NOI18N
        panelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 80));
        panelRegistro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(false);
        jButton2.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JLabel textoUsuario10;
    private javax.swing.JLabel textoUsuario11;
    private javax.swing.JLabel textoUsuario6;
    private javax.swing.JLabel textoUsuario7;
    private javax.swing.JLabel textoUsuario8;
    private javax.swing.JLabel textoUsuario9;
    // End of variables declaration//GEN-END:variables
}
