/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.administrador;

import aplicacion.Empleado;
import gui.ModeloTablaEmpleados;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.JTableHeader;

/**
 *
 * @author alumnogreibd
 */
public class VGestionEmpleados extends javax.swing.JPanel {

    aplicacion.FachadaAplicacion fa;
    private boolean nuevo;
    /**
     * Creates new form VGestionUsuarios
     */
    public VGestionEmpleados(aplicacion.FachadaAplicacion fa) {
        initComponents();
        this.fa=fa;
        nuevo=false;
        ModeloTablaEmpleados tp = new ModeloTablaEmpleados();
        initComponents();
        tablaEmpleados.setModel(tp);
        tp.setFilas(fa.obtenerEmpleados(this.FiltroId.getText()));
        tablaEmpleados.changeSelection(0,0,false,false);
        ErrorID.setVisible(false);
        LConfirmar.setVisible(false);
        LAlta.setVisible(true);
        BtAlta.setVisible(true);
        labelEliminado.setVisible(false);
        ErrorID.setVisible(false);
        AltaCorrecta.setVisible(false);
        LocalLabel.setVisible(true);
        TxLocal.setVisible(true);
        LabelActualizar.setVisible(false);
        LocalLabel.setVisible(false);
        TxPassword.setVisible(false);
        ContrasenaL1.setVisible(false);
        TxLocal.setVisible(false);
        TxTipo.setVisible(false);
        labelTipo.setVisible(false);
        labelEliminado.setVisible(false);
        ErrorAlta2.setVisible(false);

        tablaEmpleados.clearSelection();
        JTableHeader th;
        th = this.tablaEmpleados.getTableHeader();
        Font fuente = new Font("SansSerif", Font.PLAIN, 16);
        th.setFont(fuente);
        th.setForeground(new Color(255,148,42));
        th.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelActualizar = new javax.swing.JPanel();
        BtActualizar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtAlta = new javax.swing.JPanel();
        LAlta = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LConfirmar = new javax.swing.JLabel();
        DarBaja = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxNombre = new javax.swing.JTextField();
        TxDireccion = new javax.swing.JTextField();
        TxId = new javax.swing.JTextField();
        TxEmail = new javax.swing.JTextField();
        TxDni = new javax.swing.JTextField();
        TxTelefono = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxNomina = new javax.swing.JTextField();
        TxSexo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        LocalLabel = new javax.swing.JLabel();
        labelEliminado = new javax.swing.JLabel();
        AltaCorrecta = new javax.swing.JLabel();
        ErrorID = new javax.swing.JLabel();
        LabelActualizar = new javax.swing.JLabel();
        TxTipo = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        ContrasenaL1 = new javax.swing.JLabel();
        JContrasena = new javax.swing.JPasswordField();
        TxPassword = new javax.swing.JPasswordField();
        TxLocal = new javax.swing.JTextField();
        ErrorAlta2 = new javax.swing.JLabel();
        FiltroId = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(10, 550));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 10, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoPequeno.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 300, 110));

        jPanel6.setBackground(new java.awt.Color(116, 126, 173));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 600, 10));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 60, 159));
        jLabel2.setText("Gestion Empleados");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 260, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tablaEmpleados.setBackground(new java.awt.Color(255, 232, 185));
        tablaEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tablaEmpleados.setModel(new ModeloTablaEmpleados());
        tablaEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaEmpleados.setSelectionBackground(new java.awt.Color(255, 189, 72));
        tablaEmpleados.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaEmpleados.setSurrendersFocusOnKeystroke(true);
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickTabla(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 600, 180));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 230, 10));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 133, 74));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel4.setText("Id:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-google-web-search-filled-50.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 226, 154));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClick(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActualizar.setBackground(new java.awt.Color(255, 148, 42));
        panelActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelActualizarMouseClicked(evt);
            }
        });
        panelActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtActualizar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        BtActualizar.setForeground(new java.awt.Color(215, 215, 215));
        BtActualizar.setText("Actualizar");
        panelActualizar.add(BtActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-actualizar-26.png"))); // NOI18N
        jLabel15.setText("jLabel1");
        panelActualizar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 33, 36));

        jPanel1.add(panelActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 41));

        BtAlta.setBackground(new java.awt.Color(255, 148, 42));
        BtAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtDarAlta(evt);
            }
        });
        BtAlta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAlta.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        LAlta.setForeground(new java.awt.Color(215, 215, 215));
        LAlta.setText("Dar alta");
        BtAlta.add(LAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-añadir-32.png"))); // NOI18N
        jLabel18.setText("jLabel1");
        BtAlta.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 33, 36));

        LConfirmar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        LConfirmar.setForeground(new java.awt.Color(215, 215, 215));
        LConfirmar.setText("Confirmar Alta");
        BtAlta.add(LConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, -1));

        jPanel1.add(BtAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 41));

        DarBaja.setBackground(new java.awt.Color(255, 148, 42));
        DarBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DarBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DarBajaMouseClicked(evt);
            }
        });
        DarBaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(215, 215, 215));
        jLabel17.setText("Dar baja");
        DarBaja.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-eliminar-26.png"))); // NOI18N
        jLabel19.setText("jLabel1");
        DarBaja.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 33, 36));

        jPanel1.add(DarBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 200, 41));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Telefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("Id:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setText("Email:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("DNI:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        TxNombre.setBackground(new java.awt.Color(255, 232, 185));
        TxNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 220, -1));

        TxDireccion.setBackground(new java.awt.Color(255, 232, 185));
        TxDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(TxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 180, -1));

        TxId.setBackground(new java.awt.Color(255, 232, 185));
        TxId.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxIdActionPerformed(evt);
            }
        });
        jPanel1.add(TxId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        TxEmail.setBackground(new java.awt.Color(255, 232, 185));
        TxEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxEmailActionPerformed(evt);
            }
        });
        jPanel1.add(TxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, -1));

        TxDni.setBackground(new java.awt.Color(255, 232, 185));
        TxDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDniActionPerformed(evt);
            }
        });
        jPanel1.add(TxDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, -1));

        TxTelefono.setBackground(new java.awt.Color(255, 232, 185));
        TxTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(TxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel23.setText("Nómina:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        TxNomina.setBackground(new java.awt.Color(255, 232, 185));
        TxNomina.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNominaActionPerformed(evt);
            }
        });
        jPanel1.add(TxNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 220, -1));

        TxSexo.setBackground(new java.awt.Color(255, 232, 185));
        TxSexo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TxSexo.setForeground(new java.awt.Color(0, 0, 0));
        TxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "H", "M" }));
        TxSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxSexoActionPerformed(evt);
            }
        });
        jPanel1.add(TxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 50, 20));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setText("Dirección:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        LocalLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LocalLabel.setText("Local:");
        jPanel1.add(LocalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        labelEliminado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelEliminado.setForeground(new java.awt.Color(255, 51, 51));
        labelEliminado.setText("Usuario Eliminado");
        jPanel1.add(labelEliminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        AltaCorrecta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        AltaCorrecta.setForeground(new java.awt.Color(0, 153, 0));
        AltaCorrecta.setText("Usuario registrado correctamente");
        jPanel1.add(AltaCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 40));

        ErrorID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ErrorID.setForeground(new java.awt.Color(255, 51, 51));
        ErrorID.setText("ID no válido");
        jPanel1.add(ErrorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        LabelActualizar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        LabelActualizar.setForeground(new java.awt.Color(0, 153, 0));
        LabelActualizar.setText("Datos actualizados");
        jPanel1.add(LabelActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        TxTipo.setBackground(new java.awt.Color(255, 232, 185));
        TxTipo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TxTipo.setForeground(new java.awt.Color(0, 0, 0));
        TxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "transportista", "oficinista", "administrador" }));
        TxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTipoActionPerformed(evt);
            }
        });
        jPanel1.add(TxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, 20));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setText("Sexo:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        labelTipo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelTipo.setText("Tipo:");
        jPanel1.add(labelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 20));

        ContrasenaL1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ContrasenaL1.setText("Password:");
        jPanel1.add(ContrasenaL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        JContrasena.setBackground(new java.awt.Color(214, 225, 254));
        JContrasena.setForeground(new java.awt.Color(0, 0, 0));
        JContrasena.setBorder(null);
        JContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(JContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 170, 30));

        TxPassword.setBackground(new java.awt.Color(255, 232, 185));
        TxPassword.setForeground(new java.awt.Color(102, 102, 102));
        TxPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(TxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 220, -1));

        TxLocal.setBackground(new java.awt.Color(255, 232, 185));
        TxLocal.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxLocalActionPerformed(evt);
            }
        });
        jPanel1.add(TxLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 220, -1));

        ErrorAlta2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ErrorAlta2.setForeground(new java.awt.Color(255, 51, 51));
        ErrorAlta2.setText("Todos los campos son obligatorios");
        jPanel1.add(ErrorAlta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 600, 240));

        FiltroId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        FiltroId.setBorder(null);
        FiltroId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroIdActionPerformed(evt);
            }
        });
        add(FiltroId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNombreActionPerformed

    private void TxDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDireccionActionPerformed

    private void TxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxIdActionPerformed

    private void TxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxEmailActionPerformed

    private void TxDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDniActionPerformed

    private void TxTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxTelefonoActionPerformed

    private void TxNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNominaActionPerformed

    private void FiltroIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroIdActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        ModeloTablaEmpleados m;
        m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        m.setFilas(fa.obtenerEmpleados(FiltroId.getText()));
    }//GEN-LAST:event_jLabel6MouseClicked

    private void TxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxSexoActionPerformed

    private void TxLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxLocalActionPerformed

    private void panelActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActualizarMouseClicked
        // TODO add your handling code here:
        ModeloTablaEmpleados m;
        m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        if((fa.consultarId(TxId.getText()) || (TxId.getText().equals(m.getFila(tablaEmpleados.getSelectedRow()).getUsuario()))) && !TxId.getText().isEmpty())
        {
            String id=m.getFila(tablaEmpleados.getSelectedRow()).getUsuario();
            actualizarEmpleado(id);
            actualizarCampos();
            vaciarTxt();
            restablecerBoton();
            tablaEmpleados.clearSelection();
        
        }
        else{
            ErrorID.setVisible(true);
            LabelActualizar.setVisible((false));
            actualizarCampos();
            vaciarTxt();
            restablecerBoton();
            tablaEmpleados.clearSelection();
        }
        
    }//GEN-LAST:event_panelActualizarMouseClicked

    private void BtDarAlta(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtDarAlta

        tablaEmpleados.clearSelection();
        if (!nuevo) {
            AltaCorrecta.setVisible(false);
            BtAlta.setBackground(new Color(245, 184, 0));
            LConfirmar.setVisible(true);
            LAlta.setVisible(false);
            vaciarTxt();
            TxTipo.setVisible(true);
            labelTipo.setVisible(true);
            nuevo = true;
            if(TxTipo.getSelectedItem().equals("oficinista")){
                LocalLabel.setVisible(true);
                TxLocal.setVisible(true);
            }
            TxPassword.setVisible(true);
            ContrasenaL1.setVisible(true);
        } else {
            if (TxId.getText().isEmpty() || TxNombre.getText().isEmpty() || TxEmail.getText().isEmpty() || TxDireccion.getText().isEmpty() || TxTelefono.getText().isEmpty() || (TxLocal.getText().isEmpty() && TxTipo.getSelectedItem().equals("oficinista"))) {
                ErrorAlta2.setVisible(true);
                
            } 
            else if(!fa.consultarId(TxId.getText())){
                ErrorID.setVisible(true);
                labelEliminado.setVisible(false);
                
                
            }
            else {
                fa.nuevoEmpleado(TxId.getText(), TxPassword.getText(), TxDni.getText(), TxNombre.getText(), TxEmail.getText(), TxDireccion.getText(), TxTelefono.getText(), (String) TxSexo.getSelectedItem(), (String) TxTipo.getSelectedItem(),Integer.parseInt(TxNomina.getText()),null);
                AltaCorrecta.setVisible(true);
                ErrorID.setVisible(false);
                labelEliminado.setVisible(false);
                restablecerBoton();
                actualizarTabla();
                vaciarTxt();
                tablaEmpleados.clearSelection();
            }
        }
    }//GEN-LAST:event_BtDarAlta

    private void clickTabla(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTabla
        // TODO add your handling code here:
        LabelActualizar.setVisible(false);
        ModeloTablaEmpleados m;
        LabelActualizar.setVisible(false);
        AltaCorrecta.setVisible(false);
        
        labelEliminado.setVisible(false);
        m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        if(m.getFila(0)!=null){
            String tipo=m.getFila(tablaEmpleados.getSelectedRow()).getTipo();
            if(tipo.equals("oficinista")){
                LocalLabel.setVisible(true);
                TxLocal.setVisible(true);
                
            }
            else{
                LocalLabel.setVisible(false);
                TxLocal.setVisible(false);
            }
        }
        this.TxId.setText(m.getFila(tablaEmpleados.getSelectedRow()).getUsuario());
        this.TxNombre.setText(m.getFila(tablaEmpleados.getSelectedRow()).getNombre());
        this.TxEmail.setText(m.getFila(tablaEmpleados.getSelectedRow()).getCorreo());
        this.TxDireccion.setText(m.getFila(tablaEmpleados.getSelectedRow()).getDireccion());
        this.TxTelefono.setText(m.getFila(tablaEmpleados.getSelectedRow()).getTelefono());
        this.TxDni.setText(m.getFila(tablaEmpleados.getSelectedRow()).getDni());
        this.TxSexo.setSelectedItem((m.getFila(tablaEmpleados.getSelectedRow())).getSexo());
        this.TxNomina.setText(m.getFila(tablaEmpleados.getSelectedRow()).getNomina().toString());
        this.TxTipo.setSelectedItem(fa.getTipo(m.getFila(tablaEmpleados.getSelectedRow()).getUsuario()));
        if("oficinista".equals(m.getFila(tablaEmpleados.getSelectedRow()).getTipo())){
            this.TxLocal.setText(fa.trabajaEn(m.getFila(tablaEmpleados.getSelectedRow()).getUsuario()));
        }
    }//GEN-LAST:event_clickTabla

    private void JContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JContrasenaActionPerformed

    private void TxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPasswordActionPerformed

    private void TxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTipoActionPerformed
        // TODO add your handling code here:
        if(((String)TxTipo.getSelectedItem()).equals("oficinista")){
            LocalLabel.setVisible(true);
            TxLocal.setVisible(true);
        }
        else{
            LocalLabel.setVisible(false);
            TxLocal.setVisible(false);
        }
    }//GEN-LAST:event_TxTipoActionPerformed

    private void DarBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarBajaMouseClicked
        // TODO add your handling code here:
        ModeloTablaEmpleados m;
        m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        String id=m.getFila(tablaEmpleados.getSelectedRow()).getUsuario();
        fa.eliminarEmpleado(id);
        labelEliminado.setVisible(true);
        actualizarTabla();
        vaciarTxt();
        tablaEmpleados.changeSelection(0,0,false,false);
        
    }//GEN-LAST:event_DarBajaMouseClicked

    private void clearMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClick
        // TODO add your handling code here:
        restablecerBoton();
    }//GEN-LAST:event_clearMouseClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AltaCorrecta;
    private javax.swing.JLabel BtActualizar;
    private javax.swing.JPanel BtAlta;
    private javax.swing.JLabel ContrasenaL1;
    private javax.swing.JPanel DarBaja;
    private javax.swing.JLabel ErrorAlta2;
    private javax.swing.JLabel ErrorID;
    private javax.swing.JTextField FiltroId;
    private javax.swing.JPasswordField JContrasena;
    private javax.swing.JLabel LAlta;
    private javax.swing.JLabel LConfirmar;
    private javax.swing.JLabel LabelActualizar;
    private javax.swing.JLabel LocalLabel;
    private javax.swing.JTextField TxDireccion;
    private javax.swing.JTextField TxDni;
    private javax.swing.JTextField TxEmail;
    private javax.swing.JTextField TxId;
    private javax.swing.JTextField TxLocal;
    private javax.swing.JTextField TxNombre;
    private javax.swing.JTextField TxNomina;
    private javax.swing.JPasswordField TxPassword;
    private javax.swing.JComboBox TxSexo;
    private javax.swing.JTextField TxTelefono;
    private javax.swing.JComboBox TxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelEliminado;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelActualizar;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
    public void vaciarTxt() {
        ModeloTablaEmpleados m;

        m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        this.TxId.setText(null);
        this.TxEmail.setText(null);
        this.TxDni.setText(null);
        this.TxDireccion.setText(null);
        this.TxTelefono.setText(null);
        this.TxNombre.setText(null);
        this.TxNomina.setText(null);
        this.TxLocal.setText(null);
        this.TxPassword.setText(null);
        
    }
    
    public void restablecerBoton() {
        nuevo = false;
        BtAlta.setBackground(new Color(255, 148, 42));
        ErrorID.setVisible(false);
        LConfirmar.setVisible(false);
        LAlta.setVisible(true);
        //LocalLabel.setVisible(false);
        //TxLocal.setVisible(false);
        TxPassword.setVisible(false);
        ContrasenaL1.setVisible(false);
        TxTipo.setVisible(false);
        labelTipo.setVisible(false);
        ErrorAlta2.setVisible(false);
        //tablaEmpleados.clearSelection();
    }
    
    public void actualizarEmpleado(String id) {
        ModeloTablaEmpleados m;

        m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        ArrayList<Integer> datos = new ArrayList<>();
        fa.actualizarEmpleado(id, new Empleado(TxId.getText(), TxPassword.getText(), TxDni.getText(), TxNombre.getText(), TxEmail.getText(), TxDireccion.getText(), TxTelefono.getText(), (String) TxSexo.getSelectedItem(),null ,Integer.parseInt(TxNomina.getText()),null));
        LabelActualizar.setVisible(true);
        m.setFilas(fa.obtenerEmpleados(this.FiltroId.getText()));
    }
    
    public void actualizarTabla(){
        ModeloTablaEmpleados m;

        m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        m.setFilas(fa.obtenerEmpleados(this.FiltroId.getText()));
        tablaEmpleados.changeSelection(0,0,false,false);
        if(m.getFila(0)!=null){
            String tipo=m.getFila(tablaEmpleados.getSelectedRow()).getTipo();
            if(tipo.equals("oficinista")){
                LocalLabel.setVisible(true);
                TxLocal.setVisible(true);
            }
            else{
                LocalLabel.setVisible(false);
                TxLocal.setVisible(false);
            }
        }
    }
    
    private void actualizarCampos()
    {
        tablaEmpleados.changeSelection(0,0,false,false);
        ModeloTablaEmpleados m = (ModeloTablaEmpleados) tablaEmpleados.getModel();
        this.TxId.setText(m.getFila(tablaEmpleados.getSelectedRow()).getUsuario());
        this.TxNombre.setText(m.getFila(tablaEmpleados.getSelectedRow()).getNombre());
        this.TxEmail.setText(m.getFila(tablaEmpleados.getSelectedRow()).getCorreo());
        this.TxDireccion.setText(m.getFila(tablaEmpleados.getSelectedRow()).getDireccion());
        this.TxTelefono.setText(m.getFila(tablaEmpleados.getSelectedRow()).getTelefono());
        this.TxDni.setText(m.getFila(tablaEmpleados.getSelectedRow()).getDni());
        this.TxSexo.setSelectedItem((m.getFila(tablaEmpleados.getSelectedRow())).getSexo());
        this.TxTipo.setSelectedItem(fa.getTipo(m.getFila(tablaEmpleados.getSelectedRow()).getUsuario()));
        this.TxNomina.setText(m.getFila(tablaEmpleados.getSelectedRow()).getNomina().toString());
        if("oficinista".equals(m.getFila(tablaEmpleados.getSelectedRow()).getTipo())){
            this.TxLocal.setText(fa.trabajaEn(m.getFila(tablaEmpleados.getSelectedRow()).getUsuario()));
        }
    }

}
