/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.administrador;

import aplicacion.Usuario;
import aplicacion.Vehiculo;
import gui.ModeloTablaVehiculos;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;
/**
 *
 * @author alumnogreibd
 */
public class VGestionVehiculos extends javax.swing.JPanel {

    /**
     * Creates new form VGestionVehiculos
     */
    private aplicacion.FachadaAplicacion fa;
    private Usuario usr;
    private boolean nuevo;
    
    public VGestionVehiculos(aplicacion.FachadaAplicacion fa,Usuario usr) {
        this.fa=fa;
        this.usr=usr;
        initComponents();
        ModeloTablaVehiculos tv = new ModeloTablaVehiculos();
        tablaVehi.setModel(tv);
        tv.setFilas(fa.obtenerVehiculos(FiltroMatricula.getText()));
        tablaVehi.changeSelection(0,0,false,false);
        ErrorID.setVisible(false);
        LConfirmar.setVisible(false);
        LAlta.setVisible(true);
        BtAlta.setVisible(true);
        ErrorAlta1.setVisible(false);
        ErrorID.setVisible(false);
        AltaCorrecta.setVisible(false);
        LabelActualizar.setVisible(false);
        
        
        ModeloTablaVehiculos mv = (ModeloTablaVehiculos) tablaVehi.getModel();
        if(mv.getRowCount()>0){
            this.TxMatricula.setText(mv.getFila(tablaVehi.getSelectedRow()).getMatricula());
            this.TxCapacidad.setText(mv.getFila(tablaVehi.getSelectedRow()).getCapacidad().toString());
            this.TxItv.setText(mv.getFila(tablaVehi.getSelectedRow()).getItv());
            this.TxDireccion.setText(mv.getFila(tablaVehi.getSelectedRow()).getDireccion());
            this.TxTransp.setText(mv.getFila(tablaVehi.getSelectedRow()).getTrans());
        }
        
        JTableHeader th;
        th = this.tablaVehi.getTableHeader();
        Font fuente = new Font("SansSerif", Font.PLAIN, 16);
        th.setFont(fuente);
        th.setForeground(new Color(255,148,42));
        th.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        FiltroMatricula = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtActualizar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtBaja = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ContrasenaL = new javax.swing.JLabel();
        mt = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxCapacidad = new javax.swing.JTextField();
        TxDireccion = new javax.swing.JTextField();
        TxMatricula = new javax.swing.JTextField();
        TxItv = new javax.swing.JTextField();
        TxTransp = new javax.swing.JTextField();
        ErrorID = new javax.swing.JLabel();
        BtAlta = new javax.swing.JPanel();
        LConfirmar = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LAlta = new javax.swing.JLabel();
        LabelActualizar = new javax.swing.JLabel();
        TxFechaCompra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AltaCorrecta = new javax.swing.JLabel();
        ErrorAlta1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(660, 592));
        setPreferredSize(new java.awt.Dimension(660, 592));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 60, 159));
        jLabel2.setText("Gestion Vehiuculos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoPequeno.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 7, 300, 110));

        jPanel6.setBackground(new java.awt.Color(116, 126, 173));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, 610, -1));

        tablaVehi.setModel(new ModeloTablaVehiculos());
        jScrollPane1.setViewportView(tablaVehi);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 175, 580, 202));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 133, 74));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel4.setText("Matricula:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 145, -1, -1));

        FiltroMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroMatriculaActionPerformed(evt);
            }
        });
        add(FiltroMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 145, 148, -1));

        jPanel1.setBackground(new java.awt.Color(255, 226, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtActualizar.setBackground(new java.awt.Color(255, 148, 42));
        BtActualizar.setToolTipText("");
        BtActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtActualizarMouseClicked(evt);
            }
        });
        BtActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(215, 215, 215));
        jLabel14.setText("Actualizar");
        BtActualizar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-actualizar-26.png"))); // NOI18N
        jLabel15.setText("jLabel1");
        BtActualizar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 33, 36));

        jPanel1.add(BtActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 41));

        BtBaja.setBackground(new java.awt.Color(255, 148, 42));
        BtBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtBajaMouseClicked(evt);
            }
        });
        BtBaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(215, 215, 215));
        jLabel17.setText("Dar baja");
        BtBaja.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-eliminar-26.png"))); // NOI18N
        jLabel19.setText("jLabel1");
        BtBaja.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 33, 36));

        jPanel1.add(BtBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 200, 41));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Capacidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        ContrasenaL.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ContrasenaL.setText("Fecha de Compra");
        jPanel1.add(ContrasenaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        mt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mt.setText("Matricula:");
        jPanel1.add(mt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setText("ITV:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("Transportista:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        TxCapacidad.setBackground(new java.awt.Color(255, 232, 185));
        TxCapacidad.setForeground(new java.awt.Color(102, 102, 102));
        TxCapacidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCapacidadActionPerformed(evt);
            }
        });
        jPanel1.add(TxCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 210, -1));

        TxDireccion.setBackground(new java.awt.Color(255, 232, 185));
        TxDireccion.setForeground(new java.awt.Color(102, 102, 102));
        TxDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(TxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 210, -1));

        TxMatricula.setBackground(new java.awt.Color(255, 232, 185));
        TxMatricula.setForeground(new java.awt.Color(102, 102, 102));
        TxMatricula.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(TxMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, -1));

        TxItv.setBackground(new java.awt.Color(255, 232, 185));
        TxItv.setForeground(new java.awt.Color(102, 102, 102));
        TxItv.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxItv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxItvActionPerformed(evt);
            }
        });
        jPanel1.add(TxItv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 180, -1));

        TxTransp.setBackground(new java.awt.Color(255, 232, 185));
        TxTransp.setForeground(new java.awt.Color(102, 102, 102));
        TxTransp.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxTransp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTranspActionPerformed(evt);
            }
        });
        jPanel1.add(TxTransp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, -1));

        ErrorID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ErrorID.setForeground(new java.awt.Color(255, 51, 51));
        ErrorID.setText("Matricula ya existente o esta vacía");
        jPanel1.add(ErrorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        BtAlta.setBackground(new java.awt.Color(255, 148, 42));
        BtAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtAltaMouseClicked(evt);
            }
        });
        BtAlta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LConfirmar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        LConfirmar.setForeground(new java.awt.Color(215, 215, 215));
        LConfirmar.setText("Confirmar Alta");
        BtAlta.add(LConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-añadir-32.png"))); // NOI18N
        jLabel18.setText("jLabel1");
        BtAlta.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 33, 36));

        LAlta.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        LAlta.setForeground(new java.awt.Color(215, 215, 215));
        LAlta.setText("Dar alta");
        BtAlta.add(LAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jPanel1.add(BtAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 190, 41));

        LabelActualizar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        LabelActualizar.setForeground(new java.awt.Color(0, 153, 0));
        LabelActualizar.setText("Datos actualizados");
        jPanel1.add(LabelActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        TxFechaCompra.setBackground(new java.awt.Color(255, 232, 185));
        TxFechaCompra.setForeground(new java.awt.Color(102, 102, 102));
        TxFechaCompra.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxFechaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxFechaCompraActionPerformed(evt);
            }
        });
        jPanel1.add(TxFechaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 180, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setText("Dirección:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        AltaCorrecta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        AltaCorrecta.setForeground(new java.awt.Color(0, 153, 0));
        AltaCorrecta.setText("Vehículo registrado correctamente");
        jPanel1.add(AltaCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 40));

        ErrorAlta1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ErrorAlta1.setForeground(new java.awt.Color(255, 51, 51));
        ErrorAlta1.setText("Todos los campos son obligatorios");
        jPanel1.add(ErrorAlta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 410, 620, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void FiltroMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroMatriculaActionPerformed

    private void BtActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtActualizarMouseClicked
        ModeloTablaVehiculos  m = (ModeloTablaVehiculos) tablaVehi.getModel();
        if((fa.consultarMatricula(TxMatricula.getText()) || (TxMatricula.getText().equals(m.getFila(tablaVehi.getSelectedRow()).getMatricula()))) && !TxMatricula.getText().isEmpty())
        {
            String matricula=m.getFila(tablaVehi.getSelectedRow()).getMatricula();
            restablecerBoton();
            actualizarVehiculo(matricula);
            actualizarCampos();
        }
        else{ErrorID.setVisible(true);
            LabelActualizar.setVisible((false));
            actualizarCampos();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtActualizarMouseClicked

    private void BtBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtBajaMouseClicked
        restablecerBoton();
        eliminarVehiculo();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtBajaMouseClicked

    private void TxCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCapacidadActionPerformed

    private void TxDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDireccionActionPerformed

    private void TxMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxMatriculaActionPerformed

    private void TxItvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxItvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxItvActionPerformed

    private void TxTranspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTranspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxTranspActionPerformed

    private void BtAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtAltaMouseClicked
        if (!nuevo) {
            BtAlta.setBackground(new Color(245, 184, 0));
            LConfirmar.setVisible(true);
            LAlta.setVisible(false);
            vaciarTxt();
            nuevo = true;
            ContrasenaL.setVisible(true);
            TxFechaCompra.setVisible(true);
        } else {
            if (TxMatricula.getText().isEmpty() || TxCapacidad.getText().isEmpty() || TxItv.getText().isEmpty() || TxDireccion.getText().isEmpty() || TxTransp.getText().isEmpty() || TxFechaCompra.getText().isEmpty()) {
                ErrorAlta1.setVisible(true);
            } else {
                fa.registrarVehi(new Vehiculo(TxMatricula.getText(),TxItv.getText(),TxFechaCompra.getText(),Integer.parseInt(TxCapacidad.getText()),TxTransp.getText(),TxDireccion.getText()));
                AltaCorrecta.setVisible(true);
                restablecerBoton();
                actualizarTabla();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAltaMouseClicked

    private void TxFechaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxFechaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxFechaCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AltaCorrecta;
    private javax.swing.JPanel BtActualizar;
    private javax.swing.JPanel BtAlta;
    private javax.swing.JPanel BtBaja;
    private javax.swing.JLabel ContrasenaL;
    private javax.swing.JLabel ErrorAlta1;
    private javax.swing.JLabel ErrorID;
    private javax.swing.JTextField FiltroMatricula;
    private javax.swing.JLabel LAlta;
    private javax.swing.JLabel LConfirmar;
    private javax.swing.JLabel LabelActualizar;
    private javax.swing.JTextField TxCapacidad;
    private javax.swing.JTextField TxDireccion;
    private javax.swing.JTextField TxFechaCompra;
    private javax.swing.JTextField TxItv;
    private javax.swing.JTextField TxMatricula;
    private javax.swing.JTextField TxTransp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mt;
    private javax.swing.JTable tablaVehi;
    // End of variables declaration//GEN-END:variables

public void restablecerBoton(){
        nuevo = false;
        BtActualizar.setEnabled(false);
        BtAlta.setBackground(new Color(255, 148, 42));
        ErrorID.setVisible(false);
        LConfirmar.setVisible(false);
        LAlta.setVisible(true);
        ContrasenaL.setVisible(false);
        tablaVehi.changeSelection(0,0,false,false);
}

public void actualizarVehiculo(String matricula){
    
    ModeloTablaVehiculos mv;
    
    mv = (ModeloTablaVehiculos) tablaVehi.getModel();
    fa.actualizarVehi(matricula, new Vehiculo(TxMatricula.getText(), TxItv.getText(), TxFechaCompra.getText(), Integer.parseInt(TxCapacidad.getText()), TxTransp.getText(), TxDireccion.getText()));
    LabelActualizar.setVisible(true);
    mv.setFilas(fa.obtenerVehiculos(matricula));
    BtActualizar.setEnabled(false);
    
}

public void eliminarVehiculo(){
    ModeloTablaVehiculos m;

        m = (ModeloTablaVehiculos) tablaVehi.getModel();
        fa.eliminarUsuario((m.getFila(tablaVehi.getSelectedRow()).getMatricula()));
        m.setFilas(fa.obtenerVehiculos(this.FiltroMatricula.getText()));
}

    public void actualizarDatos() {
        ModeloTablaVehiculos mv;

        mv = (ModeloTablaVehiculos) tablaVehi.getModel();
        this.TxMatricula.setText(mv.getFila(tablaVehi.getSelectedRow()).getMatricula());
        this.TxItv.setText(mv.getFila(tablaVehi.getSelectedRow()).getItv());
        this.TxCapacidad.setText(mv.getFila(tablaVehi.getSelectedRow()).getCapacidad().toString());
        this.TxDireccion.setText(mv.getFila(tablaVehi.getSelectedRow()).getDireccion());
        this.TxTransp.setText(mv.getFila(tablaVehi.getSelectedRow()).getTrans());
        this.TxFechaCompra.setText(mv.getFila(tablaVehi.getSelectedRow()).getFechaCompra());
    }
    
    private void actualizarCampos()
    {
        tablaVehi.changeSelection(0,0,false,false);
        ModeloTablaVehiculos mv = (ModeloTablaVehiculos) tablaVehi.getModel();
        this.TxMatricula.setText(mv.getFila(tablaVehi.getSelectedRow()).getMatricula());
        this.TxItv.setText(mv.getFila(tablaVehi.getSelectedRow()).getItv());
        this.TxCapacidad.setText(mv.getFila(tablaVehi.getSelectedRow()).getCapacidad().toString());
        this.TxDireccion.setText(mv.getFila(tablaVehi.getSelectedRow()).getDireccion());
        this.TxTransp.setText(mv.getFila(tablaVehi.getSelectedRow()).getTrans());
        this.TxFechaCompra.setText(mv.getFila(tablaVehi.getSelectedRow()).getFechaCompra());
    }
    
    public void vaciarTxt() {
        ModeloTablaVehiculos m;

        m = (ModeloTablaVehiculos) tablaVehi.getModel();
        this.TxMatricula.setText(null);
        this.TxItv.setText(null);
        this.TxCapacidad.setText(null);
        this.TxDireccion.setText(null);
        this.TxTransp.setText(null);
        this.TxFechaCompra.setText(null);
    }

    public void actualizarTabla(){
        ModeloTablaVehiculos m;

        m = (ModeloTablaVehiculos) tablaVehi.getModel();
        m.setFilas(fa.obtenerVehiculos(FiltroMatricula.getText()));
    }

}

