/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.administrador;

import aplicacion.Paquete;
import aplicacion.Pedido;
import gui.ModeloTablaPaquetes;
import gui.ModeloTablaPedidos3;
import gui.ModeloTablaUsuarios;

/**
 *
 * @author alumnogreibd
 */
public class VGestionPaquetes extends javax.swing.JPanel {

    aplicacion.FachadaAplicacion fa;

    /**
     * Creates new form VGestionPaquetes
     * @param fa
     */
    public VGestionPaquetes(aplicacion.FachadaAplicacion fa) {
        initComponents();
        this.fa=fa;
        ModeloTablaPedidos3 tp = new ModeloTablaPedidos3();
        tablaPedidos.setModel(tp);
        tp.setFilas(fa.pedidosSinTramitar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BtBaja = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxDireccion = new javax.swing.JTextField();
        TxPaquetes = new javax.swing.JTextField();
        TxCodigo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxDestinatario = new javax.swing.JTextField();
        TxExpress = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        FiltroId = new javax.swing.JTextField();
        FiltroNombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPaquetes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(10, 550));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 10, 550));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 60, 159));
        jLabel2.setText("Gestion Pedidos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 260, -1));

        jPanel6.setBackground(new java.awt.Color(116, 126, 173));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 600, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoPequeno.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 300, 110));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-google-web-search-filled-50.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        tablaPedidos.setModel(new ModeloTablaPedidos3());
        tablaPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaPedidos.setGridColor(new java.awt.Color(255, 189, 72));
        tablaPedidos.setSelectionBackground(new java.awt.Color(255, 189, 72));
        tablaPedidos.setShowHorizontalLines(false);
        tablaPedidos.setShowVerticalLines(false);
        tablaPedidos.setSurrendersFocusOnKeystroke(true);
        tablaPedidos.getTableHeader().setResizingAllowed(false);
        tablaPedidos.getTableHeader().setReorderingAllowed(false);
        tablaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPedidos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 190, 590, 120));

        jPanel1.setBackground(new java.awt.Color(255, 226, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtBaja.setBackground(new java.awt.Color(255, 148, 42));
        BtBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtEliminar(evt);
            }
        });
        BtBaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(215, 215, 215));
        jLabel17.setText("Eliminar");
        BtBaja.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 110, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-eliminar-26.png"))); // NOI18N
        jLabel19.setText("jLabel1");
        BtBaja.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 33, 36));

        jPanel1.add(BtBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 380, 41));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Dirección");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setText("Codigo");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        TxDireccion.setBackground(new java.awt.Color(255, 232, 185));
        TxDireccion.setForeground(new java.awt.Color(102, 102, 102));
        TxDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxDireccion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxDireccion.setEnabled(false);
        TxDireccion.setFocusable(false);
        TxDireccion.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxDireccion.setSelectionColor(new java.awt.Color(0, 0, 0));
        TxDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(TxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, -1));

        TxPaquetes.setBackground(new java.awt.Color(255, 232, 185));
        TxPaquetes.setForeground(new java.awt.Color(102, 102, 102));
        TxPaquetes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxPaquetes.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxPaquetes.setEnabled(false);
        TxPaquetes.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxPaquetes.setSelectionColor(new java.awt.Color(0, 0, 0));
        TxPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPaquetesActionPerformed(evt);
            }
        });
        jPanel1.add(TxPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 220, -1));

        TxCodigo.setBackground(new java.awt.Color(255, 232, 185));
        TxCodigo.setForeground(new java.awt.Color(102, 102, 102));
        TxCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxCodigo.setEnabled(false);
        TxCodigo.setSelectionColor(new java.awt.Color(0, 0, 0));
        TxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(TxCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setText("Nº Paquetes");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 30));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel23.setText("Express:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setText("Destinatario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        TxDestinatario.setBackground(new java.awt.Color(255, 232, 185));
        TxDestinatario.setForeground(new java.awt.Color(102, 102, 102));
        TxDestinatario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        TxDestinatario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxDestinatario.setEnabled(false);
        TxDestinatario.setFocusable(false);
        TxDestinatario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxDestinatario.setSelectionColor(new java.awt.Color(0, 0, 0));
        TxDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDestinatarioActionPerformed(evt);
            }
        });
        jPanel1.add(TxDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, -1));

        TxExpress.setBackground(new java.awt.Color(255, 232, 185));
        TxExpress.setContentAreaFilled(false);
        TxExpress.setEnabled(false);
        TxExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxExpressActionPerformed(evt);
            }
        });
        jPanel1.add(TxExpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 421, 600, 130));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 133, 74));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel4.setText("Codigo:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 500, 10));

        FiltroId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        FiltroId.setBorder(null);
        FiltroId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroIdActionPerformed(evt);
            }
        });
        add(FiltroId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 420, -1));

        FiltroNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        FiltroNombre.setBorder(null);
        FiltroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroNombreActionPerformed(evt);
            }
        });
        add(FiltroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, -1));

        tablaPaquetes.setModel(new ModeloTablaPaquetes());
        jScrollPane3.setViewportView(tablaPaquetes);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 319, 590, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        ModeloTablaUsuarios tp = new ModeloTablaUsuarios();
        tablaPedidos.setModel(tp);
        tp.setFilas(fa.obtenerUsuarios(this.FiltroId.getText(), this.FiltroNombre.getText()));
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tablaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPedidosMouseClicked
        // TODO add your handling code here:
        ModeloTablaPedidos3 m;
        ModeloTablaPaquetes p;
        m = (ModeloTablaPedidos3) tablaPedidos.getModel();
        p = (ModeloTablaPaquetes) tablaPaquetes.getModel();
        this.TxCodigo.setText(m.getFila(tablaPedidos.getSelectedRow()).getCodigo().toString());
        this.TxExpress.setSelected(m.getFila(tablaPedidos.getSelectedRow()).isExpress());
        this.TxDireccion.setText(m.getFila(tablaPedidos.getSelectedRow()).getDireccion());
        this.TxDestinatario.setText(m.getFila(tablaPedidos.getSelectedRow()).getDestinatario());
        this.TxPaquetes.setText(Integer.toHexString(m.getFila(tablaPedidos.getSelectedRow()).getNumPaquetes()));
        p.setFilas(fa.obtenerPaquetes(m.getFila(tablaPedidos.getSelectedRow()).getCodigo().toString()));
    }//GEN-LAST:event_tablaPedidosMouseClicked

    private void TxDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDireccionActionPerformed

    private void TxPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPaquetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPaquetesActionPerformed

    private void TxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCodigoActionPerformed

    private void FiltroIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroIdActionPerformed

    private void FiltroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroNombreActionPerformed

    private void TxDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDestinatarioActionPerformed

    private void TxExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxExpressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxExpressActionPerformed

    private void BtEliminar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtEliminar
        // TODO add your handling code here:
        ModeloTablaPedidos3 m;
        ModeloTablaPaquetes p;
        Paquete paquete;
        m = (ModeloTablaPedidos3) tablaPedidos.getModel();
        p = (ModeloTablaPaquetes) tablaPaquetes.getModel();
        int [] Indices;
        Indices = tablaPaquetes.getSelectedRows();
        Pedido pedido=m.getFila(tablaPedidos.getSelectedRow());
        if(Indices.length!=0){
            if(Indices.length==pedido.getNumPaquetes()){
                fa.eliminarPedido(pedido.getCodigo());
            }
            else{
                for(int i=0;i<Indices.length;i++){
                    paquete=p.getFila(Indices[i]);
                    fa.elimarPaquete(paquete.getPedido(), paquete.getCodigo());
                }
            }
        }
        else{
            fa.eliminarPedido(pedido.getCodigo());
        }
        actualizarTablaPedidos();
        p.vaciarLista();
        vaciaText();
    }//GEN-LAST:event_BtEliminar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtBaja;
    private javax.swing.JTextField FiltroId;
    private javax.swing.JTextField FiltroNombre;
    private javax.swing.JTextField TxCodigo;
    private javax.swing.JTextField TxDestinatario;
    private javax.swing.JTextField TxDireccion;
    private javax.swing.JCheckBox TxExpress;
    private javax.swing.JTextField TxPaquetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaPaquetes;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
    
    public void actualizarTablaPedidos() {
        ModeloTablaPedidos3 tp;
        tp = (ModeloTablaPedidos3) tablaPedidos.getModel();
        tp.setFilas(fa.pedidosSinTramitar());
    }
    public void vaciaText(){
        this.TxCodigo.setText(null);
        this.TxExpress.setSelected(false);
        this.TxDireccion.setText(null);
        this.TxDestinatario.setText(null);
        this.TxPaquetes.setText(null);
    }
}
