/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.administrador;

import aplicacion.FachadaAplicacion;
import aplicacion.Usuario;

/**
 *
 * @author alumnogreibd
 */
public class VPerfilAdmin extends javax.swing.JPanel {
    
    private Usuario usuario;
    private FachadaAplicacion fa;
    /**
     * Creates new form VPerfilAdmin
     */
    public VPerfilAdmin(FachadaAplicacion fa,Usuario usr) {
        initComponents();
        this.fa=fa;
        this.usuario=usr;
        this.TxId.setText(usuario.getUsuario());
        this.TxCorreo.setText(usuario.getCorreo());
        this.TxDni.setText(usuario.getDni());
        this.TxNombre.setText(usuario.getNombre());
        this.TxTelefono.setText(usuario.getTelefono());
        this.sexo.setSelectedItem(usuario.getSexo());
        this.TxDireccion.setText(usuario.getDireccion());
        JLabelMensaje.setVisible(false);
        LabelActualizar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxId = new javax.swing.JTextField();
        TxNombre = new javax.swing.JTextField();
        TxCorreo = new javax.swing.JTextField();
        TxTelefono = new javax.swing.JTextField();
        TxDni = new javax.swing.JTextField();
        Actualizar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jActualizar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<String>();
        jLabel17 = new javax.swing.JLabel();
        TxDireccion = new javax.swing.JTextField();
        JLabelMensaje = new javax.swing.JLabel();
        LabelActualizar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxId.setBackground(new java.awt.Color(255, 226, 154));
        TxId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TxId.setForeground(new java.awt.Color(0, 0, 0));
        TxId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxId.setBorder(null);
        add(TxId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 470, 30));

        TxNombre.setBackground(new java.awt.Color(255, 226, 154));
        TxNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TxNombre.setForeground(new java.awt.Color(0, 0, 0));
        TxNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxNombre.setBorder(null);
        add(TxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 208, 470, 30));

        TxCorreo.setBackground(new java.awt.Color(255, 226, 154));
        TxCorreo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TxCorreo.setForeground(new java.awt.Color(0, 0, 0));
        TxCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxCorreo.setBorder(null);
        add(TxCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 256, 470, 30));

        TxTelefono.setBackground(new java.awt.Color(255, 226, 154));
        TxTelefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TxTelefono.setForeground(new java.awt.Color(0, 0, 0));
        TxTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxTelefono.setBorder(null);
        add(TxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 304, 470, 30));

        TxDni.setBackground(new java.awt.Color(255, 226, 154));
        TxDni.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TxDni.setForeground(new java.awt.Color(0, 0, 0));
        TxDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxDni.setBorder(null);
        add(TxDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 352, 470, 30));

        Actualizar.setBackground(new java.awt.Color(255, 133, 74));
        Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-actualizar-26.png"))); // NOI18N
        jLabel10.setText("jLabel1");

        jActualizar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jActualizar.setForeground(new java.awt.Color(215, 215, 215));
        jActualizar.setText("Actualizar");
        jActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ActualizarLayout = new javax.swing.GroupLayout(Actualizar);
        Actualizar.setLayout(ActualizarLayout);
        ActualizarLayout.setHorizontalGroup(
            ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        ActualizarLayout.setVerticalGroup(
            ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jActualizar))
                .addContainerGap())
        );

        add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 504, -1, -1));

        jLabel16.setBackground(new java.awt.Color(65, 105, 225));
        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 133, 74));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel16.setText("DNI");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 354, -1, -1));

        jLabel15.setBackground(new java.awt.Color(65, 105, 225));
        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 133, 74));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel15.setText("Telefono");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 306, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(10, 550));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 16, -1, -1));

        jLabel14.setBackground(new java.awt.Color(65, 105, 225));
        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 133, 74));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel14.setText("Correo");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 256, -1, -1));

        jLabel13.setBackground(new java.awt.Color(65, 105, 225));
        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 133, 74));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel13.setText("Sexo");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 448, -1, -1));

        jLabel12.setBackground(new java.awt.Color(65, 105, 225));
        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 133, 74));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel12.setText("Nombre:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 210, -1, -1));

        jLabel3.setBackground(new java.awt.Color(65, 105, 225));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 133, 74));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel3.setText("Id:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        sexo.setBackground(new java.awt.Color(255, 226, 154));
        sexo.setForeground(new java.awt.Color(0, 0, 0));
        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "H", "M" }));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 448, 50, -1));

        jLabel17.setBackground(new java.awt.Color(65, 105, 225));
        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 133, 74));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-derechaNaranja.png"))); // NOI18N
        jLabel17.setText("Direccion");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 402, -1, -1));

        TxDireccion.setBackground(new java.awt.Color(255, 226, 154));
        TxDireccion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TxDireccion.setForeground(new java.awt.Color(0, 0, 0));
        TxDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxDireccion.setBorder(null);
        add(TxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 470, 30));

        JLabelMensaje.setForeground(new java.awt.Color(255, 0, 0));
        JLabelMensaje.setText("Id ya existente!");
        add(JLabelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 20));

        LabelActualizar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        LabelActualizar.setForeground(new java.awt.Color(0, 153, 0));
        LabelActualizar.setText("Datos actualizados correctamente");
        add(LabelActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 478, -1, 16));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 60, 159));
        jLabel2.setText("datos personales");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 260, -1));

        jPanel6.setBackground(new java.awt.Color(116, 126, 173));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 600, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoPequeno.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 300, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void jActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarMouseClicked
        // TODO add your handling code here:
        if((fa.consultarId(TxId.getText()) || (TxId.getText().equals(usuario.getUsuario()))) && !TxId.getText().isEmpty()){
            JLabelMensaje.setVisible(false);
            usuario.setCorreo(TxCorreo.getText());
            usuario.setDireccion(TxDireccion.getText());
            usuario.setDni(TxDni.getText());
            usuario.setNombre(TxNombre.getText());
            usuario.setSexo((String) sexo.getSelectedItem());
            usuario.setTelefono(TxTelefono.getText());
            usuario.setUsuario(TxId.getText());
            fa.actualizar(usuario);
            LabelActualizar.setVisible(true);
        }
        else{
            JLabelMensaje.setVisible(true);
        }
    }//GEN-LAST:event_jActualizarMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    LabelActualizar.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actualizar;
    private javax.swing.JLabel JLabelMensaje;
    private javax.swing.JLabel LabelActualizar;
    private javax.swing.JTextField TxCorreo;
    private javax.swing.JTextField TxDireccion;
    private javax.swing.JTextField TxDni;
    private javax.swing.JTextField TxId;
    private javax.swing.JTextField TxNombre;
    private javax.swing.JTextField TxTelefono;
    private javax.swing.JLabel jActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> sexo;
    // End of variables declaration//GEN-END:variables
}
